/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Khoj
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  resultsCount: 6,
  khojUrl: "http://localhost:8000",
  connectedToBackend: false,
  autoConfigure: true,
  openaiApiKey: ""
};
var KhojSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("small", { text: this.getBackendStatusMessage() });
    new import_obsidian.Setting(containerEl).setName("Khoj URL").setDesc("The URL of the Khoj backend").addText((text) => text.setValue(`${this.plugin.settings.khojUrl}`).onChange(async (value) => {
      var _a;
      this.plugin.settings.khojUrl = value.trim();
      await this.plugin.saveSettings();
      (_a = containerEl.firstElementChild) == null ? void 0 : _a.setText(this.getBackendStatusMessage());
    }));
    new import_obsidian.Setting(containerEl).setName("OpenAI API Key").setDesc("Your OpenAI API Key for Khoj Chat").addText((text) => text.setValue(`${this.plugin.settings.openaiApiKey}`).onChange(async (value) => {
      this.plugin.settings.openaiApiKey = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Results Count").setDesc("The number of search results to show").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.resultsCount).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.resultsCount = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto Configure").setDesc("Automatically configure the Khoj backend").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoConfigure).onChange(async (value) => {
      this.plugin.settings.autoConfigure = value;
      await this.plugin.saveSettings();
    }));
    let indexVaultSetting = new import_obsidian.Setting(containerEl);
    indexVaultSetting.setName("Index Vault").setDesc("Manually force Khoj to re-index your Obsidian Vault").addButton((button) => button.setButtonText("Update").setCta().onClick(async () => {
      button.setButtonText("Updating \u{1F311}");
      button.removeCta();
      indexVaultSetting = indexVaultSetting.setDisabled(true);
      const progress_indicator = window.setInterval(() => {
        if (button.buttonEl.innerText === "Updating \u{1F311}") {
          button.setButtonText("Updating \u{1F318}");
        } else if (button.buttonEl.innerText === "Updating \u{1F318}") {
          button.setButtonText("Updating \u{1F317}");
        } else if (button.buttonEl.innerText === "Updating \u{1F317}") {
          button.setButtonText("Updating \u{1F316}");
        } else if (button.buttonEl.innerText === "Updating \u{1F316}") {
          button.setButtonText("Updating \u{1F315}");
        } else if (button.buttonEl.innerText === "Updating \u{1F315}") {
          button.setButtonText("Updating \u{1F314}");
        } else if (button.buttonEl.innerText === "Updating \u{1F314}") {
          button.setButtonText("Updating \u{1F313}");
        } else if (button.buttonEl.innerText === "Updating \u{1F313}") {
          button.setButtonText("Updating \u{1F312}");
        } else if (button.buttonEl.innerText === "Updating \u{1F312}") {
          button.setButtonText("Updating \u{1F311}");
        }
      }, 300);
      this.plugin.registerInterval(progress_indicator);
      await (0, import_obsidian.request)(`${this.plugin.settings.khojUrl}/api/update?t=markdown&force=true`);
      new import_obsidian.Notice("\u2705 Updated Khoj index.");
      window.clearInterval(progress_indicator);
      button.setButtonText("Update");
      button.setCta();
      indexVaultSetting = indexVaultSetting.setDisabled(false);
    }));
  }
  getBackendStatusMessage() {
    return !this.plugin.settings.connectedToBackend ? "\u2757Disconnected from Khoj backend. Ensure Khoj backend is running and Khoj URL is correctly set below." : "\u2705 Connected to Khoj backend.";
  }
};

// src/search_modal.ts
var import_obsidian3 = require("obsidian");

// src/utils.ts
var import_obsidian2 = require("obsidian");
function getVaultAbsolutePath(vault) {
  let adaptor = vault.adapter;
  if (adaptor instanceof import_obsidian2.FileSystemAdapter) {
    return adaptor.getBasePath();
  }
  return "";
}
async function configureKhojBackend(vault, setting, notify = true) {
  let mdInVault = `${getVaultAbsolutePath(vault)}/**/*.md`;
  let khojConfigUrl = `${setting.khojUrl}/api/config/data`;
  let khoj_already_configured = await (0, import_obsidian2.request)(khojConfigUrl).then((response) => {
    setting.connectedToBackend = true;
    return response !== "null";
  }).catch((error) => {
    setting.connectedToBackend = false;
    if (notify)
      new import_obsidian2.Notice(`\u2757\uFE0FEnsure Khoj backend is running and Khoj URL is pointing to it in the plugin settings.

${error}`);
  });
  if (!setting.connectedToBackend)
    return;
  let indexName = getVaultAbsolutePath(vault).replace(/\//g, "_").replace(/ /g, "_");
  let defaultConfig = await (0, import_obsidian2.request)(`${khojConfigUrl}/default`).then((response) => JSON.parse(response));
  let khojDefaultIndexDirectory = getIndexDirectoryFromBackendConfig(defaultConfig["content-type"]["markdown"]["embeddings-file"]);
  let khojDefaultChatDirectory = getIndexDirectoryFromBackendConfig(defaultConfig["processor"]["conversation"]["conversation-logfile"]);
  let khojDefaultChatModelName = defaultConfig["processor"]["conversation"]["model"];
  await (0, import_obsidian2.request)(khoj_already_configured ? khojConfigUrl : `${khojConfigUrl}/default`).then((response) => JSON.parse(response)).then((data) => {
    if (!khoj_already_configured) {
      data["content-type"] = {
        "markdown": {
          "input-filter": [mdInVault],
          "input-files": null,
          "embeddings-file": `${khojDefaultIndexDirectory}/${indexName}.pt`,
          "compressed-jsonl": `${khojDefaultIndexDirectory}/${indexName}.jsonl.gz`
        }
      };
    } else if (!data["content-type"]["markdown"]) {
      data["content-type"]["markdown"] = {
        "input-filter": [mdInVault],
        "input-files": null,
        "embeddings-file": `${khojDefaultIndexDirectory}/${indexName}.pt`,
        "compressed-jsonl": `${khojDefaultIndexDirectory}/${indexName}.jsonl.gz`
      };
    } else if (data["content-type"]["markdown"]["input-filter"].length != 1 || data["content-type"]["markdown"]["input-filter"][0] !== mdInVault) {
      let khojIndexDirectory = getIndexDirectoryFromBackendConfig(data["content-type"]["markdown"]["embeddings-file"]);
      data["content-type"]["markdown"] = {
        "input-filter": [mdInVault],
        "input-files": null,
        "embeddings-file": `${khojIndexDirectory}/${indexName}.pt`,
        "compressed-jsonl": `${khojIndexDirectory}/${indexName}.jsonl.gz`
      };
    }
    if (!setting.openaiApiKey) {
      delete data["processor"];
    } else if (!khoj_already_configured || !data["processor"]) {
      data["processor"] = {
        "conversation": {
          "conversation-logfile": `${khojDefaultChatDirectory}/conversation.json`,
          "model": khojDefaultChatModelName,
          "openai-api-key": setting.openaiApiKey
        }
      };
    } else if (!data["processor"]["conversation"]) {
      data["processor"]["conversation"] = {
        "conversation-logfile": `${khojDefaultChatDirectory}/conversation.json`,
        "model": khojDefaultChatModelName,
        "openai-api-key": setting.openaiApiKey
      };
    } else if (data["processor"]["conversation"]["openai-api-key"] !== setting.openaiApiKey) {
      data["processor"]["conversation"] = {
        "conversation-logfile": data["processor"]["conversation"]["conversation-logfile"],
        "model": data["processor"]["conversation"]["model"],
        "openai-api-key": setting.openaiApiKey
      };
    }
    updateKhojBackend(setting.khojUrl, data);
    if (!khoj_already_configured)
      console.log(`Khoj: Created khoj backend config:
${JSON.stringify(data)}`);
    else
      console.log(`Khoj: Updated khoj backend config:
${JSON.stringify(data)}`);
  }).catch((error) => {
    if (notify)
      new import_obsidian2.Notice(`\u2757\uFE0FFailed to configure Khoj backend. Contact developer on Github.

Error: ${error}`);
  });
}
async function updateKhojBackend(khojUrl, khojConfig) {
  let requestContent = {
    url: `${khojUrl}/api/config/data`,
    body: JSON.stringify(khojConfig),
    method: "POST",
    contentType: "application/json"
  };
  await (0, import_obsidian2.request)(requestContent).then((_) => (0, import_obsidian2.request)(`${khojUrl}/api/update?t=markdown`));
}
function getIndexDirectoryFromBackendConfig(filepath) {
  return filepath.split("/").slice(0, -1).join("/");
}
async function createNote(name, newLeaf = false) {
  var _a, _b;
  try {
    let pathPrefix;
    switch (app.vault.getConfig("newFileLocation")) {
      case "current":
        pathPrefix = ((_b = (_a = app.workspace.getActiveFile()) == null ? void 0 : _a.parent.path) != null ? _b : "") + "/";
        break;
      case "folder":
        pathPrefix = this.app.vault.getConfig("newFileFolderPath") + "/";
        break;
      default:
        pathPrefix = "";
        break;
    }
    await app.workspace.openLinkText(`${pathPrefix}${name}.md`, "", newLeaf);
  } catch (e) {
    console.error("Khoj: Could not create note.\n" + e.message);
    throw e;
  }
}
async function createNoteAndCloseModal(query, modal, opt) {
  try {
    await createNote(query, opt == null ? void 0 : opt.newLeaf);
  } catch (e) {
    new import_obsidian2.Notice(e.message);
    return;
  }
  modal.close();
}

// src/search_modal.ts
var KhojSearchModal = class extends import_obsidian3.SuggestModal {
  constructor(app2, setting, find_similar_notes = false) {
    super(app2);
    this.rerank = false;
    this.query = "";
    this.app = app2;
    this.setting = setting;
    this.find_similar_notes = find_similar_notes;
    this.inputEl.hidden = this.find_similar_notes;
    this.scope.register(["Mod"], "Enter", async () => {
      this.rerank = true;
      this.inputEl.dispatchEvent(new Event("input"));
      this.rerank = false;
    });
    this.scope.register(["Shift"], "Enter", async () => {
      if (this.query != "")
        createNoteAndCloseModal(this.query, this);
    });
    this.scope.register(["Ctrl", "Shift"], "Enter", async () => {
      if (this.query != "")
        createNoteAndCloseModal(this.query, this, { newLeaf: true });
    });
    const modalInstructions = [
      {
        command: "\u2191\u2193",
        purpose: "to navigate"
      },
      {
        command: "\u21B5",
        purpose: "to open"
      },
      {
        command: import_obsidian3.Platform.isMacOS ? "cmd \u21B5" : "ctrl \u21B5",
        purpose: "to rerank"
      },
      {
        command: "esc",
        purpose: "to dismiss"
      }
    ];
    this.setInstructions(modalInstructions);
    this.setPlaceholder("Search with Khoj \u{1F985}...");
  }
  async onOpen() {
    if (this.find_similar_notes) {
      let file = this.app.workspace.getActiveFile();
      if (file && file.extension === "md") {
        this.rerank = true;
        this.inputEl.value = await this.app.vault.read(file).then((file_str) => file_str.slice(0, 8e3));
        this.inputEl.dispatchEvent(new Event("input"));
        this.rerank = false;
      } else {
        this.resultContainerEl.setText("Cannot find similar notes for non-markdown files");
      }
    }
  }
  async getSuggestions(query) {
    let encodedQuery = encodeURIComponent(query);
    let searchUrl = `${this.setting.khojUrl}/api/search?q=${encodedQuery}&n=${this.setting.resultsCount}&r=${this.rerank}&t=markdown`;
    let response = await (0, import_obsidian3.request)(searchUrl);
    let data = JSON.parse(response);
    let results = data.filter((result) => {
      var _a;
      return !this.find_similar_notes || !result.additional.file.endsWith((_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path);
    }).map((result) => {
      return { entry: result.entry, file: result.additional.file };
    });
    this.query = query;
    return results;
  }
  async renderSuggestion(result, el) {
    let lines_to_render = 8;
    let os_path_separator = result.file.includes("\\") ? "\\" : "/";
    let filename = result.file.split(os_path_separator).pop();
    result.entry = result.entry.replace(/---[\n\r][\s\S]*---[\n\r]/, "");
    let entry_snipped_indicator = result.entry.split("\n").length > lines_to_render ? " **...**" : "";
    let snipped_entry = result.entry.split("\n").slice(0, lines_to_render).join("\n");
    el.createEl("div", { cls: "khoj-result-file" }).setText(filename != null ? filename : "");
    let result_el = el.createEl("div", { cls: "khoj-result-entry" });
    import_obsidian3.MarkdownRenderer.renderMarkdown(snipped_entry + entry_snipped_indicator, result_el, null, null);
  }
  async onChooseSuggestion(result, _) {
    const mdFiles = this.app.vault.getMarkdownFiles();
    let file_match = mdFiles.sort((a, b) => b.path.length - a.path.length).find((file) => result.file.replace(/\\/g, "/").endsWith(file.path));
    if (file_match) {
      let resultHeading = result.entry.split("\n", 1)[0];
      let linkToEntry = `${file_match.path}${resultHeading}`;
      this.app.workspace.openLinkText(linkToEntry, "");
      console.log(`Link: ${linkToEntry}, File: ${file_match.path}, Heading: ${resultHeading}`);
    }
  }
};

// src/chat_modal.ts
var import_obsidian4 = require("obsidian");
var KhojChatModal = class extends import_obsidian4.Modal {
  constructor(app2, setting) {
    super(app2);
    this.setting = setting;
    this.scope.register([], "Enter", async () => {
      let input_el = this.contentEl.getElementsByClassName("khoj-chat-input")[0];
      let user_message = input_el.value;
      input_el.value = "";
      await this.getChatResponse(user_message);
    });
  }
  async onOpen() {
    let { contentEl } = this;
    contentEl.addClass("khoj-chat");
    contentEl.createEl("h1", { attr: { id: "khoj-chat-title" }, text: "Khoj Chat" });
    contentEl.createDiv({ attr: { id: "khoj-chat-body", class: "khoj-chat-body" } });
    let chatUrl = `${this.setting.khojUrl}/api/chat?`;
    let response = await (0, import_obsidian4.request)(chatUrl);
    let chatLogs = JSON.parse(response).response;
    chatLogs.forEach((chatLog) => {
      this.renderMessageWithReferences(chatLog.message, chatLog.by, chatLog.context, new Date(chatLog.created));
    });
    contentEl.createEl("input", {
      attr: {
        type: "text",
        id: "khoj-chat-input",
        autofocus: "autofocus",
        placeholder: "Chat with Khoj \u{1F985} [Hit Enter to send message]",
        class: "khoj-chat-input option"
      }
    }).addEventListener("change", (event) => {
      this.result = event.target.value;
    });
    this.modalEl.scrollTop = this.modalEl.scrollHeight;
  }
  generateReference(messageEl, reference, index) {
    let escaped_ref = reference.replace(/"/g, '\\"');
    return messageEl.createEl("sup").createEl("abbr", {
      attr: {
        title: escaped_ref,
        tabindex: "0"
      },
      text: `[${index}] `
    });
  }
  renderMessageWithReferences(message, sender, context, dt) {
    let messageEl = this.renderMessage(message, sender, dt);
    if (context && !!messageEl) {
      context.map((reference, index) => this.generateReference(messageEl, reference, index + 1));
    }
  }
  renderMessage(message, sender, dt) {
    let message_time = this.formatDate(dt != null ? dt : new Date());
    let emojified_sender = sender == "khoj" ? "\u{1F985} Khoj" : "\u{1F914} You";
    let chat_body_el = this.contentEl.getElementsByClassName("khoj-chat-body")[0];
    let chat_message_el = chat_body_el.createDiv({
      attr: {
        "data-meta": `${emojified_sender} at ${message_time}`,
        class: `khoj-chat-message ${sender}`
      }
    }).createDiv({
      attr: {
        class: `khoj-chat-message-text ${sender}`
      },
      text: `${message}`
    });
    this.modalEl.scrollTop = this.modalEl.scrollHeight;
    return chat_message_el;
  }
  formatDate(date) {
    let time_string = date.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: false });
    let date_string = date.toLocaleString("en-IN", { year: "numeric", month: "short", day: "2-digit" }).replace(/-/g, " ");
    return `${time_string}, ${date_string}`;
  }
  async getChatResponse(query) {
    if (!query || query === "")
      return;
    this.renderMessage(query, "you");
    let encodedQuery = encodeURIComponent(query);
    let chatUrl = `${this.setting.khojUrl}/api/chat?q=${encodedQuery}`;
    let response = await (0, import_obsidian4.request)(chatUrl);
    let data = JSON.parse(response);
    this.renderMessage(data.response, "khoj");
  }
};

// src/main.ts
var Khoj = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "search",
      name: "Search",
      checkCallback: (checking) => {
        if (!checking && this.settings.connectedToBackend)
          new KhojSearchModal(this.app, this.settings).open();
        return this.settings.connectedToBackend;
      }
    });
    this.addCommand({
      id: "similar",
      name: "Find similar notes",
      editorCheckCallback: (checking) => {
        if (!checking && this.settings.connectedToBackend)
          new KhojSearchModal(this.app, this.settings, true).open();
        return this.settings.connectedToBackend;
      }
    });
    this.addCommand({
      id: "chat",
      name: "Chat",
      checkCallback: (checking) => {
        if (!checking && this.settings.connectedToBackend && !!this.settings.openaiApiKey)
          new KhojChatModal(this.app, this.settings).open();
        return !!this.settings.openaiApiKey;
      }
    });
    this.addRibbonIcon("search", "Khoj", (_) => {
      this.settings.connectedToBackend ? new KhojSearchModal(this.app, this.settings).open() : new import_obsidian5.Notice(`\u2757\uFE0FEnsure Khoj backend is running and Khoj URL is pointing to it in the plugin settings`);
    });
    this.addSettingTab(new KhojSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (this.settings.autoConfigure) {
      await configureKhojBackend(this.app.vault, this.settings);
    }
  }
  async saveSettings() {
    if (this.settings.autoConfigure) {
      await configureKhojBackend(this.app.vault, this.settings, false);
    }
    this.saveData(this.settings);
  }
};
